/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emerson.calculadora.view;

import emerson.calculadora.bean.CalculadoraBean;
import emerson.calculadora.controller.CalculadoraController;
import javax.swing.JOptionPane;

/**
 *
 * @author emerson
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNum1 = new javax.swing.JTextField();
        jTFRes = new javax.swing.JTextField();
        jTFNum2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jBSoma = new javax.swing.JButton();
        jBSubtracao = new javax.swing.JButton();
        jBMult = new javax.swing.JButton();
        jBDivsao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Primeira Calculadora");

        btnFechar.setMnemonic('F');
        btnFechar.setText("Fechar");
        btnFechar.setToolTipText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primeira Calculadora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 13), new java.awt.Color(38, 53, 201))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(38, 53, 201));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 53, 201));
        jLabel1.setText("Numero1*:");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 53, 201));
        jLabel2.setText("Numero2*:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 53, 201));
        jLabel3.setText("Resultado:");

        jTFRes.setEditable(false);
        jTFRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFRes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTFNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jButton2.setMnemonic('B');
        jButton2.setText("Botão Novo");
        jButton2.setToolTipText("Botão Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBSoma.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        jBSoma.setForeground(new java.awt.Color(0, 45, 255));
        jBSoma.setMnemonic('F');
        jBSoma.setText("+");
        jBSoma.setToolTipText("Fechar");
        jBSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaActionPerformed(evt);
            }
        });

        jBSubtracao.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        jBSubtracao.setForeground(new java.awt.Color(0, 45, 255));
        jBSubtracao.setMnemonic('F');
        jBSubtracao.setText("-");
        jBSubtracao.setToolTipText("Fechar");
        jBSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubtracaoActionPerformed(evt);
            }
        });

        jBMult.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        jBMult.setForeground(new java.awt.Color(0, 45, 255));
        jBMult.setMnemonic('F');
        jBMult.setText("X");
        jBMult.setToolTipText("Fechar");
        jBMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultActionPerformed(evt);
            }
        });

        jBDivsao.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        jBDivsao.setForeground(new java.awt.Color(0, 45, 255));
        jBDivsao.setMnemonic('F');
        jBDivsao.setText("/");
        jBDivsao.setToolTipText("Fechar");
        jBDivsao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivsaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jBSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBMult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBDivsao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSoma)
                    .addComponent(jBSubtracao)
                    .addComponent(jBMult)
                    .addComponent(jBDivsao))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        jBSoma.getAccessibleContext().setAccessibleName("");
        jBSubtracao.getAccessibleContext().setAccessibleName("");
        jBMult.getAccessibleContext().setAccessibleName("");
        jBDivsao.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String num1 = jTFNum1.getText();
        jTFRes.setText(num1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaActionPerformed
        CalculadoraBean calculadoraBean = validaEntradas();
        if (calculadoraBean != null) {

            Float result = CalculadoraController.soma(calculadoraBean);
            jTFRes.setText(result.toString());
        }
    }//GEN-LAST:event_jBSomaActionPerformed

    private void jBSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubtracaoActionPerformed
        CalculadoraBean calculadoraBean = validaEntradas();
        if (calculadoraBean != null) {

            Float result = CalculadoraController.subtracao(calculadoraBean);
            jTFRes.setText(result.toString());
        }
    }//GEN-LAST:event_jBSubtracaoActionPerformed

    private void jBMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultActionPerformed
        CalculadoraBean calculadoraBean = validaEntradas();
        if (calculadoraBean != null) {

            Float result = CalculadoraController.multiplicacao(calculadoraBean);
            jTFRes.setText(result.toString());
        }
    }//GEN-LAST:event_jBMultActionPerformed

    private void jBDivsaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivsaoActionPerformed
        CalculadoraBean calculadoraBean = validaEntradas();
        if (calculadoraBean != null) {

            Float result = CalculadoraController.divisao(calculadoraBean);
            jTFRes.setText(result.toString());
        }
    }//GEN-LAST:event_jBDivsaoActionPerformed

    private void jTFResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFResActionPerformed

    }//GEN-LAST:event_jTFResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    private Float retornaValorNumerico(String texto) {
        Float val = Float.parseFloat(texto);
        return val;
    }

    private CalculadoraBean validaEntradas() {
        CalculadoraBean calculadoraBean = new CalculadoraBean();
        if (jTFNum1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [numero1] não pode ser vazio!");
            jTFNum1.grabFocus();
            return null;
        } else {
            try {
                calculadoraBean.setN1(Float.parseFloat(jTFNum1.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo [Numero1] deve ser numérico!");
                jTFNum1.setText("");
                jTFNum1.grabFocus();
                return null;
            }
        }
        if (jTFNum2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo [numero1] não pode ser vazio!");
            jTFNum2.grabFocus();
            return null;
        } else {
            try {
                calculadoraBean.setN2(Float.parseFloat(jTFNum2.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo [Numero2] deve ser numérico!");
                jTFNum2.setText("");
                jTFNum2.grabFocus();
                return null;
            }

        }
        return calculadoraBean;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton jBDivsao;
    private javax.swing.JButton jBMult;
    private javax.swing.JButton jBSoma;
    private javax.swing.JButton jBSubtracao;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFNum1;
    private javax.swing.JTextField jTFNum2;
    private javax.swing.JTextField jTFRes;
    // End of variables declaration//GEN-END:variables

}
